export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ARTICLE_ROUTE = '/article'
export const CREATEARTICLE_ROUTE = '/crarticle'
export const ACCAUNT_ROUTE = '/accaunt'
export const HOME_ROUTE = '/'
