export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ARTICLE_ROUTE = '/store'
export const CREATEARTICLE_ROUTE = '/basket'
export const ACCAUNT_ROUTE = '/device'
export const ONEARTICLE_ROUTE = '/oneArticle'
export const HOME_ROUTE = '/home'
